--- 
title: "The Social Life of Neighborhoods Tutorials: Data Processing & Mapping Tutorials"
author: "Professor Forrest Stuart, TA: Francine Stephens"
date: "Last updated: `r format(Sys.time(), '%B %d, %Y')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a website with tutorials for the Social Life of Neighborhoods offered in SOC 176/276. The output format for this example is bookdown::gitbook."
---

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

# About

The following is a series of tutorials specifically designed for **The Social Life of Neighborhoods (SOC 176/SOC 276/AFRICAAM 76B/CSRE 176B/URBANST 179)** course. The course assignments and final story map require collecting and analyzing information about neighborhoods and
other urban spaces. In the tutorials, you will be introduced to tools that will allow you to gather, process, and visualize data so that you can complete the assignments and create your own story map. No prior experience or familiarity with quantitative data or GIS/spatial software is assumed in the tutorials. If you have some prior experience, you will likely be able to skim over anything that looks familiar and focus on new techniques.

These tutorials are a work in progress. Recommendations for improving the content are welcome. If you run across typos, grammatical errors, or confusing language, please send your comments, questions, and feedback to Francine Stephens at [fis@stanford.edu](mailto:fis@stanford.edu). 

Each tutorial is a chapter in this website. You can navigate through the chapters using the sidebar. At the top of this page, you will see settings options in the navigation bar. Hover over the icons in the top bar to hide the sidebar or change the font and color scheme to your preference. 

